feat: login with jwttoken
BookJamm/BE pull request #58
Opened 2023-07-21 05:09 UTC by ranunclulus

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 [#]
#57 
## 📄 개요
- 이메일이랑 비밀번호를 바디에 넣어 주면
- jwt 토큰을 드려요
- 유통기한은 365일!!

## 🔁 변경 사항
### 변경 내용을 적어주세요 (커밋 번호를 적어주세요)
- 왜, 어떻게 변경했는지 상세한 설명을 작성해주세요 (생략 가능)

## 📸 스크린샷
이메일이 틀릴 경우
<img width="785" alt="image" src="https://github.com/BookJamm/BE/assets/87214089/4aa04f44-a192-4f41-ba21-7898cd07421e">
비밀번호가 틀릴 경우
<img width="784" alt="image" src="https://github.com/BookJamm/BE/assets/87214089/7cc54652-b9a1-4c65-9c88-71deca5c6e16">
비활성화 계정일 경우
<img width="657" alt="image" src="https://github.com/BookJamm/BE/assets/87214089/8edbdca3-8ed1-48b6-a06b-60043036b25c">
로그인에 성공했을 경우
<img width="824" alt="image" src="https://github.com/BookJamm/BE/assets/87214089/0536f856-ecb5-42ea-a330-2f74e8141dcb">

## 👀 기타 더 이야기해볼 점
이후 자신의 기록을 보는 데서는 jwt 토큰 비교를 추가해야 할 것 같심다

2023-07-21 09:17 UTC, ranunclulus commented
accessToken, refreshToken 둘 다 발급하기로 수정

2023-07-21 09:21 UTC, ranunclulus commented
jwtMiddleware -> middleware로 넣기

2023-07-21 09:21 UTC, ranunclulus commented
refresh user table에 넣는지 구글링 고고

2023-07-22 01:58 UTC, ranunclulus commented
<img width="844" alt="image" src="https://github.com/BookJamm/BE/assets/87214089/6a276d1e-8069-4dd4-a815-db84a8456773">
 accesstoken 1h
refreshtoken 14d로 바꿔서 올렸습니다!

2023-07-23 17:58 UTC, eomgerm requested changes
코드 짜시느라 정말 고생 많으셨어요...!! 고민도 많이 하신 흔적이 곳곳에 보이는데 정말 머리 아프셨을 것 같아요ㅠㅠ 다만 여기저기 제 기준으로는 아쉬운 부분들이 많아서 나중에 같이 고민해 봐야할 것 같습니다!

2023-07-23 17:58 UTC, eomgerm commented on config/jsonWebToken.js
코드 복붙을 하신 건가요?!! 이 부분만 ES5 문법이라...!! ES6로 변경할 필요가 있어보입니다!

2023-07-23 17:58 UTC, eomgerm commented on config/middlewares.js
사용자 검증을 위한 미들웨어는 없네요?! 이 부분은 나중에 추가하실 예정인가요? 그리고 불필요한 import 문도 삭제해야 할 것 같습니다 :)

2023-07-23 17:58 UTC, eomgerm commented on src/auth/authController.js
controller에 서비스 로직이 통합되어 있는 것 같아요ㅠㅠ! 컨트롤러는 정말 요청 파싱 및 응답만 해야 한다는 게 저의 개발 규칙인데... 제가 봤을 때는 유저 확인, 유저 정보 받아오기, 비활성화 계정 검증 등은 다 서비스로 들어가야 할 로직 같습니다... 이 부분에 대해서는 같이 고민해 볼 필요가 있을 것 같습니다.

2023-07-26 15:02 UTC, eomgerm approved these changes
고생하셨습니다. 머지해용

2023-07-26 15:03 UTC, merged