feat: Post record apis update
BookJamm/BE pull request #8
Opened 2023-09-23 14:28 UTC by 1000chw

기록 작성하는 api update

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #7 

## 📌 개요
- Record 관련 api 업데이트하기

## 🔁 변경 사항
- .eslintrc.js 수정함
## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2023-09-23 16:14 UTC, eomgerm requested changes
고생 많으셨어요! 독학하면서 기능까지 구현하기가 쉽지 않았을텐데 이렇게까지 좋은 코드를 짜시다니!! 몇가지 아쉬운 점들 리뷰했으니 확인 부탁드립니다 :)

2023-09-23 16:14 UTC, eomgerm commented on src/record/dto/record.dto.ts
> +  isNotPublic: number;
이 값은 boolean으로 받아야 할 것 같습니다!

2023-09-23 16:14 UTC, eomgerm commented on src/record/dto/record.dto.ts
> +  commentNotAllowed: number;
이 값도 boolean!

2023-09-23 16:14 UTC, eomgerm commented on src/record/dto/record.dto.ts
> +  commentCount: number = 0;
이건 불필요 할 것 같아요.

2023-09-23 16:14 UTC, eomgerm commented on src/record/dto/record.dto.ts
> +  likeCount: number = 0;
이것도 불필요한 것 같습니다...!

2023-09-23 16:14 UTC, eomgerm commented on src/record/entities/record-like.entity.ts
> +export class RecordLikes extends BaseEntity {
entity class는 단수로만 사용하기로 해요~! RecordLike로 부탁드립니다.

2023-09-23 16:14 UTC, eomgerm commented on src/record/entities/record.entity.ts
> +  commentNotAllowed: number;
이걸 boolean으로 설정하면 불러올 때는 boolean으로 불러와지고 db에 저장하면 실제로는 db 타입으로 입력될 것 같은데... 한 번 해보시겠어요?

2023-09-23 16:14 UTC, eomgerm commented on src/record/entities/record.entity.ts
> +  isNotPublic: number;
이것도 마찬가지로 boolean으로 바꿔도 정상 동작할 것 같은데... 확인 부탁드립니다!

2023-09-23 16:14 UTC, eomgerm commented on src/record/entities/record.repository.ts
복잡한 query문이 없는 경우에는 굳이 repository class를 생성하지 않아도 될 것 같아요.

2023-09-23 16:14 UTC, eomgerm commented on src/record/record.controller.ts
> +  @Post(':recordId/images')
이번에 제가 api 개편을 하면서 이미지 업로드 endpoint를 삭제하고 하나의 api로 묶기로 했어요! 자세한 건 review 생성하는 controller랑 service 참고해보시겠어요?

2023-09-23 16:14 UTC, eomgerm commented on src/record/record.service.ts
> +    if (!activity) {
이런식으로 place랑 activity를 따로 확인하면 아래의 문제가 발생할 것 같아요.
place나 record 둘 중 하나가 undefined인 경우 요청 자체는 문제가 없으나 findOneBy에서 에러가 발생할 것 같아요.
차라리 recordDto.placeId, recordDto.activityId 둘 중 하나라도 존재하는 지 확인하고 만약 존재하는 것에 대해서만 db 존재 여부를 확인해야 할 듯 합니다.

2023-09-23 16:25 UTC, eomgerm requested changes
리뷰 추가합니다!

2023-09-23 16:25 UTC, eomgerm commented on src/record/record.service.ts
> +    const record: Record = new Record(
이건 저도 방금 생각난 건데 RecordDto 클래스에 toRecord 메서드를 추가하면 코드를 더 깔끔하게 할 수 있을 것 같아요... 자세한 내용은 저희 한 번 회의해요~!

2023-09-23 16:25 UTC, eomgerm commented on src/record/record.service.ts
> +    return { created: true, recordId: record.recordId };
저는 정상적으로 생성되면 굳이 created 값은 필요없을 것 같습니다!

2023-09-23 16:25 UTC, eomgerm commented on src/record/dto/post-record-response.dto.ts
> +export class postRecordResponse {
왜 이친구만 앞글자가 소문자인가요?!

2023-09-23 20:07 UTC, 1000chw commented on src/record/entities/record.repository.ts
repository class에 query 추가 했어요!

2023-09-24 03:39 UTC, eomgerm commented on src/record/record.service.ts
> +  async getFriendsRecords(userId: number, friendId?: number, last?: number) {
친구 기록만 보고 싶을 때는 차라리 GET /api/users/:userId/records로 분리하시는 건 어떤가요? 하나에 두 가지 로직이 있어서 나중에 유지보수 할 때 어려울 수 있을 것 같아요

2023-09-24 03:40 UTC, eomgerm commented on src/record/record.controller.ts
> +      GlobalResponseCode.OK,
OK 응답 보낼 때는 굳이 파라미터에 넣지 않으셔도 됩니다! 디폴트값이 OK예요

2023-09-24 03:41 UTC, eomgerm commented on src/record/entities/record.repository.ts
> +    const records = (await query.getRawMany()).map(res => plainToInstance(RecordLIstResponse, res));
plainToInstance(RecordListResponse, await query.getRawMany())로 해도 된다고 합니다! 리스트도 지원한다고 하네용

2023-09-24 03:42 UTC, eomgerm commented on src/record/dto/record-list-response.dto.ts
> +  imagesUrls: string[];
이미지는 ImageResponse Dto를 이용해주세요!

2023-09-24 03:42 UTC, eomgerm commented on src/record/dto/record-list-response.dto.ts
> +  placeId: number;
장소랑 장소이름은 place: {placeId, name} 이런식으로 묶는 게 좋을 것 같아요.

2023-09-24 03:45 UTC, eomgerm commented on src/record/dto/record-list-response.dto.ts
db에서 불러온 값을 dto에 매핑하기 위해서 plainToInstnace를 쓰잖아요.
그런데 타입스크립트는 런타임 환경에서는 타입 체크를 안해주기 때문에 (왜냐하면 사실상 돌아가는 건 자바스크립트니까)
타입이 다르다고 에러가 발생하거나 그러지 않아요!
그래서 실제로 query된 객체는 string이고 이걸 number로 바꾸고 싶으면 원하는 변수에 @Type(() => Number) 데코레이터를 추가해보셔요~!
이러면 plainToInstance할 때 자동으로 타입이 변환된답니다

2023-09-24 03:49 UTC, eomgerm requested changes
좋습니다! 리뷰 확인 부탁드려요

2023-09-24 03:51 UTC, eomgerm commented on src/record/entities/record.entity.ts
> +  places: Place;
places => place 기록에는 장소 하나만 지정할 수 있지 않나요?

2023-09-24 03:53 UTC, eomgerm commented on src/record/entities/record.repository.ts
> +      console.log(typeof record.recordId);
불필요한 console.log는 삭제해주세요! 아마 eslint에서 알아서 잡아줄텐데... eslint 경고가 안 떴나요?

2023-12-05 07:44 UTC, eomgerm commented
불필요한 API

2023-12-05 07:44 UTC, closed without merging